/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mezzsy.myapplication.swig;

public class SwigDemo {
  public static void helloFromNative() {
    SwigDemoJNI.helloFromNative();
  }

}
