/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mezzsy.swig;

public interface UnixConstants {
  public final static int CONST_VALUE_1 = UnixJNI.CONST_VALUE_1_get();
  public final static int CONST_VALUE_2 = UnixJNI.CONST_VALUE_2_get();
}
